embers/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from . import settings
from materias.views import lista_de_materias

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lista_de_materias, name='index'),
    path('about_us/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    path('', include('login.urls')),
    path('', include('tutorial.urls')),

    path('materia/', include('materias.urls')),

    # server是一个视图函数server(request, path), 通过path找到文件然后返回response
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout, name='logout'),
]

login/models.py
from django.db import models

# Create your models here.

class Aluno(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=128)
    email = models.EmailField(unique=True)
    password = models.CharField(blank=False, null=False, max_length=256)
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=1000000)
    init = models.DecimalField(max_digits=12, decimal_places=2, default=1000000)
    createdAt = models.DateTimeField(auto_now_add=True)
    tipo_user = models.CharField(blank=False, null=False, max_length=256, default='ALUNO')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = 'Alunos'

login/views.py
from django.shortcuts import render, redirect
from login.models import *


def index(request):
    return render(request, 'index.html')


def login(request):
    if request.session.get('user_id', ''):
        return redirect("/")
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember = request.POST.get('remember')
        message = 'check input contents'
        if username.strip() and password.strip():
            try:
                user = Aluno.objects.get(username=username)
            except:
                message = 'username does not exist!'
                return render(request, 'login/login.html', {'message': message})
            if user.password == password:
                response = redirect('/')
                request.session['user_id'] = user.id
                if remember == "on":
                    response.set_cookie('username', user.username, max_age=7 * 24 * 3600)
                    response.set_cookie('userid', user.id, max_age=7 * 24 * 3600)
                # request.POST.session['user_name'] = user.username
                return response
            else:
                message = 'incorrect password'
                return render(request, 'login/login.html', {'message': message})
        else:
            return render(request, 'login/login.html', {'message': message})
    return render(request, 'login/login.html')


def registration(request):
    if request.method == 'POST':
        message = 'check input content'
        username = request.POST.get('username')
        email = request.POST.get('email')
        password_01 = request.POST.get('password_01')
        password_02 = request.POST.get('password_02')
        if username.strip() and email.strip() and password_01.strip() and password_02.strip():
            if password_01 != password_02:
                message = 'as senhas estão diferentes'
                return render(request, 'login/registration.html', {'message': message})
            else:
                same_username = Aluno.objects.filter(username=username)
                if same_username:
                    message = 'username already exists!'
                    return render(request, 'login/registration.html', {'message': message})
                same_email = Aluno.objects.filter(email=email)
                if same_email:
                    message = 'email has been used!'
                    return render(request, 'login/registration.html', {'message': message})
                # create user info
                new_user = Aluno()
                new_user.username = username
                new_user.password = password_01
                new_user.email = email
                new_user.save()
                return redirect('/login/')
    return render(request, 'login/registration.html')


def logout(request):
    if not request.session.get('user_id', None):
        return redirect('/login/')
    request.session.flush()
    return redirect('/')

login/templates/login/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
    <div data-overlay class="min-vh-100 bg-light d-flex flex-column justify-content-md-center">
      <section class="py-3">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-5 col-md-6">
              <div class="card card-body shadow">
                <h1 class="h5 text-center">Fazer Login</h1>
                <form action="{% url 'login:login' %}" method="post">
                    {% if message %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                    {% csrf_token %}
                  <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Usuário">
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Senha">
                  </div>
                  <button class="btn btn-primary btn-block" type="submit">Entrar</button>
                </form>
              </div>
              <div class="text-center text-small mt-3">
                Ainda não tem uma conta? <a href="{% url 'login:registration' %}">Crie uma conta!</a>
              </div>
              <div class="text-center text-small mt-3">
                É professor? <a href="http://127.0.0.1:8000/admin/">Faça login por aqui!</a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
{% endblock %}

login/templates/login/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div data-overlay class="min-vh-100 bg-light d-flex flex-column justify-content-md-center o-hidden">
      <section class="py-3">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-5 col-md-6 mb-5 mb-md-0">
              <div class="card card-body shadow">
                <h1 class="h5 text-center">Crie sua conta</h1>
                <form action="{% url 'login:registration' %}" method="post">
                    {% if message %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                    {% csrf_token %}
                  <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Usuário">
                  </div>
                  <div class="form-group">
                    <input type="email" class="form-control" name="email" placeholder="Email">
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password_01" placeholder="Senha">
                    <small>Senha deve ter no mínimo 8 caracteres</small>
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password_02" placeholder="Confirme Senha">
                  </div>
                  <div>
                    <input class = "form-control" type="text" placeholder="Ano que irá cursar" list="Ano">
                    <datalist id="Ano">
                      <option value="">Série:</option>
                      <option value="5º ano">Fundamental 1</option>
                    </datalist>
                  </div>
                  <br><br>
                  <button class="btn btn-primary btn-block" type="submit">Cadastre-se</button>
                </form>
              </div>
              <div class="text-center text-small mt-3">
                Ja tem uma conta? <a href="{% url 'login:login' %}">Entre aqui</a>
              </div>
            </div>
            <div class="col-md-6 col-lg-auto ml-lg-5 ">
              <div class="mb-5">
                <div class="mb-2 mb-md-4" data-aos="fade-left" data-aos-delay="100">
                  <div class="media rounded align-items-center pl-3 pr-3 pr-md-4 py-2 bg-white shadow-sm">
                    <img src="{% static 'img/about-2.jpg' %}" alt="Harvey Derwent avatar image" class="avatar avatar-sm flex-shrink-0 mr-3">
                    <div class="text-dark mb-0">&ldquo;Estamos aqui para te ajudar a caminhar para o futuro&rdquo;</div>
                  </div>
                </div>
                <div class="mb-2 mb-md-4" data-aos="fade-left" data-aos-delay="200">
                  <div class="media rounded align-items-center pl-3 pr-3 pr-md-4 py-2 bg-white shadow-sm">
                    <img src="{% static 'img/about-1.jpg' %}" alt="Harvey Derwent avatar image" class="avatar avatar-sm flex-shrink-0 mr-3">
                    <div class="text-dark mb-0">&ldquo;O conhecimento abre caminhos.&rdquo;</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
{% endblock %}