embers/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from . import settings
from materias.views import lista_de_materias

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lista_de_materias, name='index'),
    path('about_us/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    path('', include('login.urls')),
    path('', include('tutorial.urls')),

    path('materia/', include('materias.urls')),

    # server是一个视图函数server(request, path), 通过path找到文件然后返回response
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout, name='logout'),
]

materias/urls.py
from django.urls import path, re_path
from django.conf.urls import include
from . import views

app_name = 'materias'

urlpatterns = [
    path('cadastro/', views.cadastrar_materia, name = 'cadastrar_materia'),
    path('assunto/', views.lista_de_materias_assunto, name = 'cadastrar_assunto'),
    path('cadastroAssunto/', views.cadastrar_assunto, name = 'cadastrarAssunto'),
    path('inicio/', views.lista_de_materias, name= 'inicio'),
    path('agenda/', views.mostrar_agenda, name= 'mostrar_agenda'),
    path('assuntoMateria/', views.mostrar_assunto, name= 'mostrar_assunto'),
    path('<slug>/', views.DetalheMateria.as_view(), name="materia"),
]

tutorial/urls.py
from django.urls import path

from . import views

app_name = 'tutorial'

urlpatterns = [
    path('tutorial/', views.intro, name='intro'),
]

templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    About us
{% endblock %}

{% block content %}
    <div class="bg-primary-3 o-hidden" data-overlay>
        <section class="text-dark pb-0">
            <div class="container pb-5">
                <div class="row justify-content-center text-center">
                    <div class="col-md-9 col-lg-8 col-xl-7">
                        <h1 class="display-3">Um Grupo focado 
                            <mark data-aos="highlight-text" data-aos-delay="250">em melhoras na educação</mark>
                        </h1>
                        <p class="lead mb-0">Os devs também estão mudando o mundo</p>

                    </div>
                </div>
            </div>
            <div class="position-absolute w-50 h-100 top left" data-jarallax-element="100 50">
                <div class="blob blob-4 bg-gradient w-100 h-100 top left"></div>
            </div>
            <div class="divider divider-bottom bg-white"></div>
        </section>
    </div>

    <section class="pb-0">
        <div class="container">
            <div class="row section-title justify-content-center text-center">
                <div class="col-md-9 col-lg-8 col-xl-7">
                    <h3 class="display-4">Nossos
                        <mark data-aos="highlight-text" data-aos-delay="250">membros</mark>
                    </h3>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <ul class="avatar-group avatar-group-lg flex-wrap justify-content-center">
                            <li>
                                <div><img src="{% static 'img/avatars/avator-1.jpg' %}" alt=" profile image"
                                          class="avatar avatar-xl"></div>
                                <p class="lead">Victor Torres</p>
                            </li>
                            <li>
                                <div><img src="{% static 'img/avatars/avator-2.jpg' %}" alt=" profile image"
                                          class="avatar avatar-xl"></div>
                                <p class="lead">Kleverson</p>
                            </li>
                            <li>
                                <div><img src="{% static 'img/avatars/avator-3.jpg' %}" alt=" profile image"
                                          class="avatar avatar-xl"></div>
                                <p class="lead">Roberto</p>
                            </li>
                            <li>
                                <div><img src="{% static 'img/avatars/avator-4.jpg' %}" alt=" profile image"
                                          class="avatar avatar-xl"></div>
                                <p class="lead">Vitor Dorico</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}
    {% endblock %}| TCC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bootstrap HTML template and UI kit by Medium Rare">
    <!-- Begin loading animation -->
    <link href="{% static 'css/loaders/loader-pulse.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!-- End loading animation -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/introjs.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/bootstrap-table.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&display=swap"
      rel="stylesheet"
    />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</head>

<body>
<div class="loader">
    <div class="loading-animation"></div>
</div>

<div class="navbar-container">
    <nav class="navbar navbar-expand-lg navbar-light" data-overlay data-sticky="top">
        <div class="container">

            <a class="navbar-brand navbar-brand-dynamic-color fade-page" href="{% url 'index' %}">
                <img alt="Embers" data-inject-svg src="{% static 'img/logos/logo.svg' %}">
            </a>


            {% if request.session.user_id %}
                <div class="d-flex align-items-center order-lg-3">
                    <a href="{% url 'login:logout' %}"
                       class="btn btn-danger ml-lg-4 mr-3 mr-md-4 mr-lg-0 d-none d-sm-block order-lg-3">Sair</a>
                    <button aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                            data-target=".navbar-collapse" data-toggle="collapse" type="button">
                        <img alt="Navbar Toggler Open Icon" class="navbar-toggler-open icon icon-sm" data-inject-svg
                             src="{% static 'img/icons/interface/icon-menu.svg' %}">
                        <img alt="Navbar Toggler Close Icon" class="navbar-toggler-close icon icon-sm" data-inject-svg
                             src="{% static 'img/icons/interface/icon-x.svg' %}">
                    </button>
                </div>
                <div class="collapse navbar-collapse order-3 order-lg-2 justify-content-lg-end" id="navigation-menu">
                    <ul class="navbar-nav my-3 my-lg-0">
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'index' %}" role="button">Home</a>
                        </li>
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'tutorial:intro' %}" role="button">Tutorial</a>
                        </li>
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'materias:mostrar_agenda' %}" role="button">Agenda</a>
                        </li>
                    </ul>
                </div>
            {% else %}
                {#not Sign in#}
                <div class="d-flex align-items-center order-lg-3">
                    <a href="{% url 'login:login' %}"
                       class="btn btn-primary ml-lg-4 mr-3 mr-md-4 mr-lg-0 d-none d-sm-block order-lg-3">Entrar</a>
                    <button aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                            data-target=".navbar-collapse" data-toggle="collapse" type="button">
                        <img alt="Navbar Toggler Open Icon" class="navbar-toggler-open icon icon-sm" data-inject-svg
                             src="{% static 'img/icons/interface/icon-menu.svg' %}">
                        <img alt="Navbar Toggler Close Icon" class="navbar-toggler-close icon icon-sm" data-inject-svg
                             src="{% static 'img/icons/interface/icon-x.svg' %}">
                    </button>
                </div>
                <div class="collapse navbar-collapse order-3 order-lg-2 justify-content-lg-end" id="navigation-menu">
                    <ul class="navbar-nav my-3 my-lg-0">
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'index' %}" role="button">Home</a>
                        </li>
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'about_us' %}" role="button">Sobre nós</a>
                        </li>
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'tutorial:intro' %}" role="button">Tutorial</a>
                        </li>
                        <li class="nav-item">
                            <a aria-expanded="false" aria-haspopup="true" class=" nav-link nav-item"
                               href="{% url 'contact_us' %}" role="button">Contate a gente</a>
                        </li>
                    </ul>
                </div>
            {% endif %}


        </div>
    </nav>
</div>

<div class="overflow-hidden">
    {% block content %}
    {% endblock %}
</div>

<footer class="bg-primary-4 text-white links-white pb-4 footer-1">
    <div class="container">
        <div class="row">
            <div class="col-xl-auto mr-xl-5 col-md-3">
                <h5>Home</h5>
                <ul class="nav flex-row flex-md-column">
                    <li class="nav-item mr-3 mr-md-0">
                        <a href="{% url 'tutorial:intro' %}" class="nav-link fade-page px-0 py-2">Tutorial</a>
                    </li>
                    <li class="nav-item mr-3 mr-md-0">
                        <a href="{% url 'about_us' %}" class="nav-link fade-page px-0 py-2">Sobre nós</a>
                    </li>
                    <li class="nav-item mr-3 mr-md-0">
                        <a href="{% url 'contact_us' %}" class="nav-link fade-page px-0 py-2">Contate a gente</a>
                    </li>
                </ul>
            </div>
            <div class="col mt-4 mt-md-0 mt-lg-5 mt-xl-0 order-lg-4 order-xl-3">
            </div>
            <div class="col-lg mt-2 mt-md-5 mt-lg-0 order-lg-3 order-xl-4">

            </div>
        </div>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class="row flex-column flex-lg-row align-items-center justify-content-center justify-content-lg-between text-center text-lg-left">
            <div class="col-auto">
                <div class="d-flex flex-column flex-sm-row align-items-center text-small">
                    <div class="text-muted">&copy; 2022 Page protected by reCAPTCHA and subject to Google's <a
                            href="https://www.google.com/policies/privacy/" target="_blank">Política e Privacidade</a> e <a
                            href="https://policies.google.com/terms" target="_blank">Termos de Serviço</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<a href="#top" class="btn btn-primary rounded-circle btn-back-to-top" data-smooth-scroll data-aos="fade-up"
   data-aos-offset="2000" data-aos-mirror="true" data-aos-once="false">
    <img src="{% static 'img/icons/interface/icon-arrow-up.svg' %}" alt="Icon" class="icon bg-white" data-inject-svg>
</a>


<!-- Required vendor scripts (Do not remove) -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

<!-- Optional Vendor Scripts (Remove the plugin script here and comment initializer script out of index.js if site does not use that feature) -->

<!-- AOS (Animate On Scroll - animates elements into view while scrolling down) -->
<script type="text/javascript" src="{% static 'js/aos.js' %}"></script>
<!-- Clipboard (copies content from browser into OS clipboard) -->
<script type="text/javascript" src="{% static 'js/clipboard.min.js' %}"></script>
<!-- Fancybox (handles image and video lightbox and galleries) -->
<script type="text/javascript" src="{% static 'js/jquery.fancybox.min.js' %}"></script>
<!-- Flatpickr (calendar/date/time picker UI) -->
<script type="text/javascript" src="{% static 'js/flatpickr.min.js' %}"></script>
<!-- Flickity (handles touch enabled carousels and sliders) -->
<script type="text/javascript" src="{% static 'js/flickity.pkgd.min.js' %}"></script>
<!-- Ion rangeSlider (flexible and pretty range slider elements) -->
<script type="text/javascript" src="{% static 'js/ion.rangeSlider.min.js' %}"></script>
<!-- Isotope (masonry layouts and filtering) -->
<script type="text/javascript" src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<!-- jarallax (parallax effect and video backgrounds) -->
<script type="text/javascript" src="{% static 'js/jarallax.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jarallax-video.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jarallax-element.min.js' %}"></script>
<!-- jQuery Countdown (displays countdown text to a specified date) -->
<script type="text/javascript" src="{% static 'js/jquery.countdown.min.js' %}"></script>
<!-- jQuery smartWizard facilitates steppable wizard content -->
<script type="text/javascript" src="{% static 'js/jquery.smartWizard.min.js' %}"></script>
<!-- Plyr (unified player for Video, Audio, Vimeo and Youtube) -->
<script type="text/javascript" src="{% static 'js/plyr.polyfilled.min.js' %}"></script>
<!-- Prism (displays formatted code boxes) -->
<script type="text/javascript" src="{% static 'js/prism.js' %}"></script>
<!-- ScrollMonitor (manages events for elements scrolling in and out of view) -->
<script type="text/javascript" src="{% static 'js/scrollMonitor.js' %}"></script>
<!-- Smooth scroll (animation to links in-page)-->
<script type="text/javascript" src="{% static 'js/smooth-scroll.polyfills.min.js' %}"></script>
<!-- SVGInjector (replaces img tags with SVG code to allow easy inclusion of SVGs with the benefit of inheriting colors and styles)-->
<script type="text/javascript" src="{% static 'js/svg-injector.umd.production.js' %}"></script>
<!-- TwitterFetcher (displays a feed of tweets from a specified account)-->
<script type="text/javascript" src="{% static 'js/twitterFetcher_min.js' %}"></script>
<!-- Typed text (animated typing effect)-->
<script type="text/javascript" src="{% static 'js/typed.min.js' %}"></script>
<!-- Required theme scripts (Do not remove) -->
<script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
<!-- For intro -->
<script type="text/javascript" src="{% static 'js/intro.min.js' %}"></script>
<!-- Removes page load animation when window is finished loading -->
<script type="text/javascript">
    window.addEventListener("load", function () {
        document.querySelector('body').classList.add('loaded');
    });
</script>
{% block script_content %}
{% endblock %}
<script>
    function searchSym() {
        var sym = $("#symText").val()
        window.location.href = "/search/" + sym;
    }


</script>
</body>

</html>

templates/contact_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Contact us
{% endblock %}

{% block content %}
    <div class="bg-gradient p-0 o-hidden" data-overlay>
      <section class="pb-0">
        <div class="container">
          <div class="text-white">
            <div class="row section-title justify-content-center text-center">
              <div class="col-md-9 col-lg-8 col-xl-7">
                <h1 class="display-3">Estamos aqui para te ajudar!</h1>
                <div class="lead">Se você tem alguma dúvida, deixe aqui!</div>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div>
              <form class="card card-body shadow" data-form-email novalidate action="/forms/smtp.php">
                <div class="form-row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="planner-name">Nome</label>
                      <input type="text" name="contact-name" class="form-control" id="planner-name" required>
                      <div class="invalid-feedback">
                        Por favor, escreva seu nome.
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="planner-email">Email</label>
                      <input type="email" name="contact-email" class="form-control" id="planner-email" placeholder="seuemail@email.com" required>
                      <div class="invalid-feedback">
                        Por favor, escreva o seu e-mail!
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for="planner-phone">Telefone (opcional)</label>
                      <input type="tel" name="contact-phone" class="form-control" id="planner-phone" required>
                      <div class="invalid-feedback">
                        Por favor, escreva seu telefone.
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label for="planner-message">Como podemos te ajudar?</label>
                  <textarea name="message" id="planner-message" rows="10" class="form-control" required></textarea>
                  <div class="invalid-feedback">
                    Por favor, escreva suas dúvidas.
                  </div>
                </div>
                <div class="d-flex flex-column flex-wrap flex-md-row justify-content-between align-items-center">
                  <div class="custom-control custom-checkbox mb-3 mb-md-0">
                    <input type="checkbox" class="custom-control-input" id="planner-agree" required>
                    <label class="custom-control-label" for="planner-agree">Eu concordo com os <a target="_blank" href="https://policies.google.com/terms?hl=pt-BR">Termos &amp; Condições</a>
                    </label>
                    <div class="invalid-feedback">
                      Por favor, aceite os termos.
                    </div>
                  </div>
                  <div class="d-none alert alert-success w-100 my-md-3" role="alert" data-success-message>
                    Obrigado, um membro do nosso time irá entrar em contato.
                  </div>
                  <div class="d-none alert alert-danger w-100 my-md-3" role="alert" data-error-message>
                    Por favor, preencha os campos corretamente.
                  </div>
                  <div data-recaptcha data-sitekey="INSERT_YOUR_RECAPTCHA_V2_SITEKEY_HERE" data-size="invisible" data-badge="bottomleft"></div>
                  <button class="btn btn-primary btn-loading" type="submit" data-loading-text="Sending">
                    <!-- Icon for loading animation -->
                    <svg class="icon bg-white" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <title>Icon For Loading</title>
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g>
                          <polygon points="0 0 24 0 24 24 0 24" opacity="0"></polygon>
                        </g>
                        <path d="M12,4 L12,6 C8.6862915,6 6,8.6862915 6,12 C6,15.3137085 8.6862915,18 12,18 C15.3137085,18 18,15.3137085 18,12 C18,10.9603196 17.7360885,9.96126435 17.2402578,9.07513926 L18.9856052,8.09853149 C19.6473536,9.28117708 20,10.6161442 20,12 C20,16.418278 16.418278,20 12,20 C7.581722,20 4,16.418278 4,12 C4,7.581722 7.581722,4 12,4 Z"
                        fill="#000000" fill-rule="nonzero" transform="translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "></path>
                      </g>
                    </svg>
                    <span>Enviar menssagem</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="divider divider-bottom bg-white"></div>
      </section>
    </div>
    <section>
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-auto" data-aos="fade-up">
            <div class="px-md-4 px-lg-5 mb-5 mb-md-0">
              <h5>Nosso email</h5>
              <a href="#" class="lead">sistemaDeApoio@gmail.com</a>
            </div>
          </div>
          <div class="col-md-auto" data-aos="fade-up" data-aos-delay="100">
            <div class="px-md-4 px-lg-5 mb-5 mb-md-0">
              <h5>Endereço</h5>
              <address>
                <p>Av. Francisco Pignatari, 650</p>
                <p>Vila Gustavo Correia - Carapicuíba</p>
                <p>São Paulo - CEP:  06310-390</p>
                <p>Brasil</p>
              </address>
              <a href="https://www.google.com.br/maps/dir//Av.+Francisco+Pignatari,+650++Vila+Gustavo+Correia+-+Carapicu%C3%ADba++S%C3%A3o+Paulo+-+CEP:+06310-390++Brasil/@-23.5344539,-46.8348296,14z/data=!4m2!4m1!3e3">Chegue até a gente!</a>
            </div>
          </div>
          <div class="col-md-auto" data-aos="fade-up" data-aos-delay="200">
            <div class="px-md-4 px-lg-5 mb-5 mb-md-0">
              <h5>Ligue para gente</h5>
              <a href="#" class="lead">11 4184 8404</a>
            </div>
          </div>
        </div>
      </div>
    </section>
<!--{#    <div data-overlay class="min-vh-100 bg-light d-flex flex-column justify-content-md-center">#}-->
<!--{#        <div class="row justify-content-center">#}-->
<!--{#            <div class="col-xl-2 col-lg-5 col-md-6">#}-->
<!--{#                <h1>Contact Us!</h1>#}-->
<!--{#                <h3>We are</h3>#}-->
<!--{#                <p>Cao Lei z5170034@ad.unsw.edu.au</p>#}-->
<!--{#                <p>Liwen Hu liwen.hu@student.mail.unsw.edu.au</p>#}-->
<!--{#                <p>Yue Sun z5238570@ad.unsw.edu.au</p>#}-->
<!--{#                <p>Yiren Hu z5148244@ad.unsw.edu.au</p>#}-->
<!--{#                <p>Di Wu z5231299@ad.unsw.edu.au</p>#}-->
<!--{##}-->
<!--{#            </div>#}-->
<!--{#        </div>#}-->
<!--{#    </div>#}-->

{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Error
{% endblock %}
{% block content %}

        <div>
            <section class="pb-0">
                <div class="container">
                    <div class="jumbotron text-center p-0 text-dark rounded bg-white min-vh-50">
                        <h1>Error page!</h1>
                        <p>{{ message }}</p>
                    </div>
                </div>
            </section>
        </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
    <div class="bg-gradient text-white p-0 o-hidden jarallax" data-overlay data-jarallax data-speed="0.5">
        <section class="pb-0">
            <img src="{% static 'img/bg.jpg' %}" alt="Image" class="jarallax-img opacity-40">
            <div class="container min-vh-40 d-flex flex-column justify-content-center">
                <div class="row justify-content-center text-center">

                    <div class="col-md-9 col-lg-8 col-xl-7">                        
                            <h1 class="display-3">Uma plataforma de estudos para você<br>
                                <mark><span data-typed-text data-loop="true" data-type-speed="90"
                                            data-strings='["aprender!!"]'></span></mark>
                            </h1>
                            <h3 class="px-xl-5" style="font-weight: 400">Uma plataforma para se aprimorar nos estudos</h3>
                            <h3 class="px-xl-5" style="font-weight: 400">Venha estudar com a gente!</h3>
                    </div>
                </div>
            </div>
            <div class="divider divider-bottom bg-primary-3"></div>
        </section>
    </div>

{% else %}
    <div class="bg-gradient text-white p-0 o-hidden jarallax" data-overlay data-jarallax data-speed="0.5">
        <section class="pb-0">
            <img src="{% static 'img/bg.jpg' %}" alt="Image" class="jarallax-img opacity-40">
            <div class="container min-vh-40 d-flex flex-column justify-content-center">
                <div class="row justify-content-center text-center">
                    <div class="col-md-9 col-lg-8 col-xl-7">                        
                        <script>
                            function searchStock() {
                                var sym = $("#searchText").val()
                                window.location.href = "/search/" + sym;
                            }
                        </script>
                    <section>
                        <div class="row justify-content-center">
                            <div class="col-xl-8 col-lg-9 text-center">
                                <h1 class="display-3">Matérias</h1> 
                            </div>
                        </div>
                    </section>
                    </div>
                </div>
            </div>
        <div>
            <div class="row">
                <div> 
                    <a class="card green" href="{% url 'portu' %}">Português</a>
                </div>
                <div>
                    <a class="card blue" href="{% url 'mat' %}">Matemática</a>
                </div>
                <div>
                    <a class="card red" href="{% url 'cien' %}">Ciências</a>
                </div>
            </div>
        </div>
        <div> 
            <div class="row">
                <div>
                    <a class="card grey" href="{% url 'ingles' %}">Inglês</a>
                </div>
                <div>
                    <a class="card dark" href="{% url 'hist' %}">História</a>
                
                </div>
                <div>
                    <a class="card pink" href="{% url 'geo' %}">Geografia</a>
                </div>
            </div>
        </div>
            <div class="divider divider-bottom bg-primary-3"></div>
        </section>
    </div>

    <section class="bg-primary-3 text-dark">
        <div class="container">
            <div class="row section-title justify-content-center text-center">
                <div class="col-md-9 col-lg-8 col-xl-7"></div>
            </div>
        </div>
    </section>
{% endif %}
{% endblock %}