embers/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from . import settings
from materias.views import lista_de_materias

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lista_de_materias, name='index'),
    path('about_us/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('contact_us/', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    path('', include('login.urls')),
    path('', include('tutorial.urls')),

    path('materia/', include('materias.urls')),

    # server是一个视图函数server(request, path), 通过path找到文件然后返回response
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout, name='logout'),
]

materias/urls.py
from django.urls import path, re_path
from django.conf.urls import include
from . import views

app_name = 'materias'

urlpatterns = [
    path('cadastro/', views.cadastrar_materia, name = 'cadastrar_materia'),
    path('assunto/', views.lista_de_materias_assunto, name = 'cadastrar_assunto'),
    path('cadastroAssunto/', views.cadastrar_assunto, name = 'cadastrarAssunto'),
    path('inicio/', views.lista_de_materias, name= 'inicio'),
    path('agenda/', views.mostrar_agenda, name= 'mostrar_agenda'),
    path('assuntoMateria/', views.mostrar_assunto, name= 'mostrar_assunto'),
    path('<slug>/', views.DetalheMateria.as_view(), name="materia"),
]

materias/models.py
from audioop import reverse
from django.utils.text import slugify
from django.db import models

# Create your models here.
class Materia(models.Model):
    nome = models.CharField(unique=True, max_length=128)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Assunto(models.Model):
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    nome = models.CharField(unique=True, max_length=128)
    link = models.URLField(blank=False, null=False, max_length=256)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Agenda(models.Model):
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    tarefa= models.CharField(unique=False, max_length=128)
    data = models.DateField()

    def __str__(self):
        return self.tarefa

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

materias/views.py
from statistics import mode
from django.shortcuts import render,redirect
from materias import models
from login.models import Aluno
from django.views.generic.detail import DetailView
from django.http.response import JsonResponse

# Create your views here.
def cadastrar_materia(request):
    try:
        if request.method == 'POST':
            materia = request.POST.get('materia')
            nova_materia = models.Materia()
            nova_materia.nome = materia
            nova_materia.save()
            return redirect('/')
        return render(request, 'materias/form.html')
    except Exception as e:
        return render(request, 'error.html', {'message': e}) 

def cadastrar_assunto(request):
    try:
        if request.method == 'POST':
            materia = request.POST.get('materiaSelecionada')
            assuntoMateria = request.POST.get('assunto')
            link = request.POST.get('link')
            materia_id = models.Materia.objects.get(id=materia)
            assunto = models.Assunto()
            assunto.materia = materia_id
            assunto.nome = assuntoMateria
            assunto.link = link
            assunto.save()
            return redirect('/')
        return render(request, '/')
    except Exception as e:
        return render(request, 'error.html', {'message': e}) 

def lista_de_materias(request):
    try:
        materias_list = models.Materia.objects.all()
        context = {
            'materias': materias_list
        }
    except Exception as e:
        return render(request, 'error.html', {'message':e.args[0]})
    return render(request, 'materias/home.html', context)

def lista_de_materias_assunto(request):
    try:
        materias_list = models.Materia.objects.all()
        context = {
            'materias': materias_list
        }
    except Exception as e:
        return render(request, 'error.html', {'message':e.args[0]})
    return render(request, 'materias/formAssunto.html', context)

def mostrar_agenda(request):
    try:
        agenda_list = models.Agenda.objects.all()
        context = {
            'tarefas': agenda_list
        }
    except Exception as e:
        return render(request, 'error.html', {'message':e.args[0]})
    return render(request, 'materias/agenda.html', context)

def mostrar_assunto(request):
    try:
        materia = request.GET.get('materia')
        assunto = models.Assunto.objects.filter(materia=materia).values_list('nome','link')
    except Exception as e:
        return render(request, 'error.html', {'message':e.args[0]})
    return JsonResponse(list(assunto), safe=False)

class DetalheMateria(DetailView):
    model = models.Materia
    template_name = 'materias/materia.html'
    context_object_name = 'materia'
    slug_url_kwarg = 'slug'

materias/templates/materias/agenda.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    Agenda
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
{% else %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <section class="bg-primary-3 text-dark">
    {% csrf_token %}
        <div class="container">
            <div class="row justify-content-center text-center">
                <h1 id="nomeMateria" class="display-3"> Veja suas tarefas por aqui </h1>
            </div>
            <br>
            <br>
            <br>
            <div class="main-materia row justify-content-center text-center">
                {% for tarefa in tarefas %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{tarefa.materia}}</h5>
                            <h5 class="card-subtitle mb-2 text-muted">{{tarefa.tarefa}}</h5>
                            <h5 class="card-subtitle mb-2 text-muted">{{tarefa.data}}</h5>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>  
    </section>
{% endif %}
{% endblock %}

materias/templates/materias/form.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    Cadastro
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
   
{% else %}
<div data-overlay class="min-vh-100 bg-light d-flex flex-column justify-content-md-center o-hidden">
    <section class="py-3">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-5 col-md-6 mb-5 mb-md-0">
              <div class="card card-body shadow">
                <h1 class="h5 text-center">Cadastre uma matéria</h1>
                <form action="{% url 'materias:cadastrar_materia' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="materia" placeholder="Matéria">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="assunto" placeholder="Assunto">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="link" placeholder="Link">
                    </div>
                    <button class="btn btn-primary btn-block" type="submit">Cadastre-se</button>
                </form>
              </div>
            </div>
          </div>
        </div>
    </section>
</div>
{% endif %}
{% endblock %}

materias/templates/materias/formAssunto.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    Cadastre um assunto para sua matéria!
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
  
{% else %}
<div data-overlay class="min-vh-100 bg-light d-flex flex-column justify-content-md-center o-hidden">
    <section class="py-3">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-5 col-md-6 mb-5 mb-md-0">
              <div class="card card-body shadow">
                <h1 class="h5 text-center">Cadastre um assunto para sua matéria!</h1>
                <form action="{% url 'materias:cadastrarAssunto' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <select name="materiaSelecionada">
                        {% for materia in materias %}
                          <option value="{{materia.id}}">{{materia.nome}}</option>
                        {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="assunto" placeholder="Assunto">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="link" placeholder="Link">
                    </div>
                    <button class="btn btn-primary btn-block" type="submit">Cadastre-se</button>
                </form>
              </div>
            </div>
          </div>
        </div>
    </section>
</div>
{% endif %}
{% endblock %}

materias/templates/materias/home.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
    <div class="bg-gradient text-white p-0 o-hidden jarallax" data-overlay data-jarallax data-speed="0.5">
        <section class="pb-0">
            <img src="{% static 'img/bg.jpg' %}" alt="Image" class="jarallax-img opacity-40">
            <div class="container min-vh-40 d-flex flex-column justify-content-center">
                <div class="row justify-content-center text-center">

                    <div class="col-md-9 col-lg-8 col-xl-7">                        
                            <h1 class="display-3">Uma plataforma de estudos para você<br>
                                <mark><span data-typed-text data-loop="true" data-type-speed="90"
                                            data-strings='["aprender!!"]'></span></mark>
                            </h1>
                            <h3 class="px-xl-5" style="font-weight: 400">Uma plataforma para se aprimorar nos estudos</h3>
                            <h3 class="px-xl-5" style="font-weight: 400">Venha estudar com a gente!</h3>
                    </div>
                </div>
            </div>
            <div class="divider divider-bottom bg-primary-3"></div>
        </section>
    </div>
{% else %}
    <div class="bg-gradient text-white p-0 o-hidden jarallax" data-overlay data-jarallax data-speed="0.5">
        <section class="pb-0">
            <img src="{% static 'img/bg.jpg' %}" alt="Image" class="jarallax-img opacity-40">
            <div class="container min-vh-40 d-flex flex-column justify-content-center">
                <div class="row justify-content-center text-center">
                    <div class="col-md-9 col-lg-8 col-xl-7">                        
                    <section>
                        <div class="row justify-content-center">
                            <div class="col-xl-8 col-lg-9 text-center">
                                <h1 class="display-3">Matérias</h1> 
                            </div>
                        </div>
                    </section>
                    </div>
                </div>
            </div>
        <div>
            <div class="row">
                {% for materia in materias %}
                    <div> 
                        <a class="card green" href='/materia/{{ materia.slug }}'>{{ materia.nome }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="divider divider-bottom bg-primary-3"></div>
        </section>
    </div>
{% endif %}
{% endblock %}

materias/templates/materias/materia.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    {{materia.nome}}
{% endblock %}

{% block content %}
{% if not request.session.user_id %}
{% else %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <section class="bg-primary-3 text-dark">
    {% csrf_token %}
        <div class="container">
            <div class="row justify-content-center text-center">
                <h1 id="nomeMateria" class="display-3"> {{materia.nome}} </h1>
                <h1 id="idMateria" class="display-3" style="visibility: hidden"> {{materia.id}} </h1>
            </div>
            <br>
            <br>
            <br>
            <div class="main-materia row justify-content-center text-center">
                <div class="center-lista">
                    <h1>Selecione a aula que gostaria de assistir</h1>
                <br>
                <div id="listaAssuntos" class="card-lista-aulas">
                
                </div>
            </div>
        </div>  
    </section>
<script>
    $(document).ready(function() {
        console.log('inicio')
        const id = document.getElementById("idMateria").innerHTML
        
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        
        buscarAssunto(id, csrftoken)
    }); 

    function buscarAssunto(materia, token){
        var teste = $.ajax({
            url : "http://127.0.0.1:8000/materia/assuntoMateria/",
            type : 'GET',
            data : {
                X_CSRF_TOKEN: token,
                materia : materia,
            },
            success: function(response){
                var card_assuntos = document.getElementById("listaAssuntos");
                for (var i = 0; i < response.length; i++) {
                    let a = document.createElement('a');
                    a.class = "botao.aula";
                    a.target = "_blank";
                    a.href = response[i][1];
                    let button = document.createElement('button');
                    button.style = "background: #069cc2; border-radius: 6px; padding: 15px; cursor: pointer; color: #fff; border: none; font-size: 16px; width:55vw;";
                    button.appendChild(document.createTextNode(response[i][0]));
                    a.appendChild(button);
                    card_assuntos.appendChild(a);
                    card_assuntos.appendChild(document.createElement('br'));
                    card_assuntos.appendChild(document.createElement('br'));
                    
                }
            }
        })
    } 

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
}
</script>
{% endif %}
{% endblock %}